### ISSUE TITLE
Failed to register worker to Raylet: IOError: Failed to read data from the socket: End of file worker_id=01000000ffffffffffffffffffffffffffffffffffffffffffffffff

### ISSUE THREAD

**Issue by wsdqy1234** [xiaomi-research/recogdrive#8]
I am running the `scripts/cache_dataset/run_caching_recogdrive_hidden_state_eval.sh`, but encountered the Raylet IOError. However, I don't know what happened and how to solve this problem. Do you have any ideas?

```shell
export NCCL_IB_DISABLE=0
export NCCL_P2P_DISABLE=0
export NCCL_SHM_DISABLE=0
export PYTHONPATH="$(pwd):${PYTHONPATH}"

MASTER_PORT=${MASTER_PORT:-63669}
PORT=${PORT:-63665}
GPUS=${GPUS:-8}
GPUS_PER_NODE=${GPUS_PER_NODE:-8}
NODES=$((GPUS / GPUS_PER_NODE))
export MASTER_PORT=${MASTER_PORT}
export PORT=${PORT}

echo "GPUS: ${GPUS}"

export MLP_ROLE_INDEX=0
export MLP_WORKER_0_HOST="127.0.0.1"
export MLP_WORKER_0_PORT=29601

torchrun \
    --nnodes=1 \
    --node_rank=$MLP_ROLE_INDEX \
    --master_addr=$MLP_WORKER_0_HOST \
    --nproc_per_node=${GPUS} \
    --master_port=$MLP_WORKER_0_PORT \
    $NAVSIM_DEVKIT_ROOT/navsim/planning/script/run_dataset_caching_multi_node.py \
    agent=recogdrive_agent \
    experiment_name=recogdrive_agent_cache \
    agent.cam_type='single' \
    agent.cache_hidden_state=True \
    agent.cache_mode=True \
    train_test_split=$TRAIN_TEST_SPLIT \
    agent.vlm_path="/home/tangzerui/daiqingyang/recogdrive/internvl_chat/ReCogDrive_VLM_2B" \
    cache_path=$CACHE_PATH  > caching_dataset_test.txt 2>&1

``` 

```powershell
W0902 09:32:38.913962 140430230890240 torch/distributed/run.py:757] 
W0902 09:32:38.913962 140430230890240 torch/distributed/run.py:757] *****************************************
W0902 09:32:38.913962 140430230890240 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0902 09:32:38.913962 140430230890240 torch/distributed/run.py:757] *****************************************
[2025-09-02 09:33:03,170][__main__][INFO] - Global Seed set to 0
[rank: 4] Seed set to 0
[2025-09-02 09:33:03,212][__main__][INFO] - Building Worker
[2025-09-02 09:33:03,309][__main__][INFO] - Global Seed set to 0
[rank: 5] Seed set to 0
[2025-09-02 09:33:03,312][__main__][INFO] - Building Worker
[2025-09-02 09:33:03,318][__main__][INFO] - Global Seed set to 0
[rank: 0] Seed set to 0
[2025-09-02 09:33:03,320][__main__][INFO] - Building Worker
[2025-09-02 09:33:03,698][__main__][INFO] - Global Seed set to 0
[rank: 1] Seed set to 0
[2025-09-02 09:33:03,701][__main__][INFO] - Building Worker
[2025-09-02 09:33:03,876][__main__][INFO] - Global Seed set to 0
[rank: 2] Seed set to 0
[2025-09-02 09:33:03,879][__main__][INFO] - Building Worker
[2025-09-02 09:33:03,983][__main__][INFO] - Global Seed set to 0
[rank: 6] Seed set to 0
[2025-09-02 09:33:03,985][__main__][INFO] - Building Worker
[2025-09-02 09:33:04,003][__main__][INFO] - Global Seed set to 0
[rank: 3] Seed set to 0
[2025-09-02 09:33:04,005][__main__][INFO] - Building Worker
[2025-09-02 09:33:04,038][__main__][INFO] - Global Seed set to 0
[rank: 7] Seed set to 0
[2025-09-02 09:33:04,040][__main__][INFO] - Building Worker
[2025-09-02 09:33:05,856][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,857][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
[2025-09-02 09:33:05,857][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,857][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
[2025-09-02 09:33:05,857][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,858][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
[2025-09-02 09:33:05,859][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,860][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
[2025-09-02 09:33:05,860][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,860][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
[2025-09-02 09:33:05,861][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,861][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
[2025-09-02 09:33:05,927][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,927][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
[2025-09-02 09:33:05,967][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Not using GPU in ray
[2025-09-02 09:33:05,967][navsim.planning.utils.multithreading.worker_ray_no_torch][INFO] - Starting ray local!
2025-09-02 09:33:12,228	INFO worker.py:1951 -- Started a local Ray instance.
2025-09-02 09:33:12,228	INFO worker.py:1951 -- Started a local Ray instance.
2025-09-02 09:33:12,235	INFO worker.py:1951 -- Started a local Ray instance.
2025-09-02 09:33:13,210	INFO worker.py:1951 -- Started a local Ray instance.
2025-09-02 09:33:13,210	INFO worker.py:1951 -- Started a local Ray instance.
2025-09-02 09:33:13,211	INFO worker.py:1951 -- Started a local Ray instance.
2025-09-02 09:33:13,212	INFO worker.py:1951 -- Started a local Ray instance.
2025-09-02 09:33:13,212	INFO worker.py:1951 -- Started a local Ray instance.
[2025-09-02 09:33:43,255 E 4443 4443] core_worker_process.cc:232: Failed to register worker to Raylet: IOError: Failed to read data from the socket: End of file worker_id=01000000ffffffffffffffffffffffffffffffffffffffffffffffff
W0902 09:33:44.059103 140430230890240 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4445 closing signal SIGTERM
*** SIGTERM received at time=1756776824 on cpu 32 ***
W0902 09:33:44.060215 140430230890240 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4447 closing signal SIGTERM
*** SIGTERM received at time=1756776824 on cpu 33 ***
W0902 09:33:44.061407 140430230890240 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4448 closing signal SIGTERM
*** SIGTERM received at time=1756776824 on cpu 31 ***
PC: @     0x7f0a92c4d87f  (unknown)  recv
    @     0x7f0a92c4e390  (unknown)  (unknown)
[2025-09-02 09:33:44,069 E 4445 4445] logging.cc:474: *** SIGTERM received at time=1756776824 on cpu 32 ***
[2025-09-02 09:33:44,069 E 4445 4445] logging.cc:474: PC: @     0x7f0a92c4d87f  (unknown)  recv
[2025-09-02 09:33:44,070 E 4445 4445] logging.cc:474:     @     0x7f0a92c4e390  (unknown)  (unknown)
PC: @     0x7fec44e8987f  (unknown)  recv
    @     0x7fec44e8a390  (unknown)  (unknown)
[2025-09-02 09:33:44,071 E 4447 4447] logging.cc:474: *** SIGTERM received at time=1756776824 on cpu 33 ***
[2025-09-02 09:33:44,071 E 4447 4447] logging.cc:474: PC: @     0x7fec44e8987f  (unknown)  recv
[2025-09-02 09:33:44,071 E 4447 4447] logging.cc:474:     @     0x7fec44e8a390  (unknown)  (unknown)
PC: @     0x7fc01c8be87f  (unknown)  recv
    @     0x7fc01c8bf390  (unknown)  (unknown)
[2025-09-02 09:33:44,073 E 4448 4448] logging.cc:474: *** SIGTERM received at time=1756776824 on cpu 31 ***
[2025-09-02 09:33:44,073 E 4448 4448] logging.cc:474: PC: @     0x7fc01c8be87f  (unknown)  recv
[2025-09-02 09:33:44,073 E 4448 4448] logging.cc:474:     @     0x7fc01c8bf390  (unknown)  (unknown)
W0902 09:33:44.062534 140430230890240 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4453 closing signal SIGTERM
*** SIGTERM received at time=1756776824 on cpu 28 ***
PC: @     0x7f411b6d987f  (unknown)  recv
    @     0x7f411b6da390  (unknown)  (unknown)
[2025-09-02 09:33:44,159 E 4453 4453] logging.cc:474: *** SIGTERM received at time=1756776824 on cpu 28 ***
[2025-09-02 09:33:44,159 E 4453 4453] logging.cc:474: PC: @     0x7f411b6d987f  (unknown)  recv
[2025-09-02 09:33:44,159 E 4453 4453] logging.cc:474:     @     0x7f411b6da390  (unknown)  (unknown)
W0902 09:33:44.160107 140430230890240 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4454 closing signal SIGTERM
*** SIGTERM received at time=1756776824 on cpu 47 ***
PC: @     0x7f3834cc387f  (unknown)  recv
    @     0x7f3834cc4390  (unknown)  (unknown)
[2025-09-02 09:33:44,200 E 4454 4454] logging.cc:474: *** SIGTERM received at time=1756776824 on cpu 47 ***
[2025-09-02 09:33:44,200 E 4454 4454] logging.cc:474: PC: @     0x7f3834cc387f  (unknown)  recv
[2025-09-02 09:33:44,201 E 4454 4454] logging.cc:474:     @     0x7f3834cc4390  (unknown)  (unknown)
W0902 09:33:44.201229 140430230890240 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4455 closing signal SIGTERM
*** SIGTERM received at time=1756776824 on cpu 28 ***
PC: @     0x7f24cbd4a87f  (unknown)  recv
    @     0x7f24cbd4b390  (unknown)  (unknown)
[2025-09-02 09:33:44,214 E 4455 4455] logging.cc:474: *** SIGTERM received at time=1756776824 on cpu 28 ***
[2025-09-02 09:33:44,214 E 4455 4455] logging.cc:474: PC: @     0x7f24cbd4a87f  (unknown)  recv
W0902 09:33:44.214461 140430230890240 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4456 closing signal SIGTERM
[2025-09-02 09:33:44,216 E 4455 4455] logging.cc:474:     @     0x7f24cbd4b390  (unknown)  (unknown)
*** SIGTERM received at time=1756776824 on cpu 47 ***
PC: @     0x7f49adbe187f  (unknown)  recv
    @     0x7f49adbe2390  (unknown)  (unknown)
[2025-09-02 09:33:44,235 E 4456 4456] logging.cc:474: *** SIGTERM received at time=1756776824 on cpu 47 ***
[2025-09-02 09:33:44,236 E 4456 4456] logging.cc:474: PC: @     0x7f49adbe187f  (unknown)  recv
[2025-09-02 09:33:44,236 E 4456 4456] logging.cc:474:     @     0x7f49adbe2390  (unknown)  (unknown)
[2025-09-02 09:33:44,331 E 4448 4448] core_worker_process.cc:232: Failed to register worker to Raylet: IOError: Failed to read data from the socket: End of file worker_id=01000000ffffffffffffffffffffffffffffffffffffffffffffffff
[2025-09-02 09:33:44,586 E 4455 4455] core_worker_process.cc:232: Failed to register worker to Raylet: IOError: Failed to read data from the socket: End of file worker_id=01000000ffffffffffffffffffffffffffffffffffffffffffffffff
E0902 09:33:47.440427 140430230890240 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 4443) of binary: /home/tangzerui/anaconda3/envs/navsim/bin/python3.9
Traceback (most recent call last):
  File "/home/tangzerui/anaconda3/envs/navsim/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/tangzerui/anaconda3/envs/navsim/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/tangzerui/anaconda3/envs/navsim/lib/python3.9/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/tangzerui/anaconda3/envs/navsim/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/tangzerui/anaconda3/envs/navsim/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tangzerui/anaconda3/envs/navsim/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by owl-10** [comment]
> I don't know why, I have commented the codes below and it worked. And I don't know if this would have any bad influence to the results.
> 
> <img alt="Image" width="800" height="480" src="https://private-user-images.githubusercontent.com/53553706/484483719-a954be72-db42-467c-9813-382da6099bf9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY5MDAyMDAsIm5iZiI6MTc1Njg5OTkwMCwicGF0aCI6Ii81MzU1MzcwNi80ODQ0ODM3MTktYTk1NGJlNzItZGI0Mi00NjdjLTk4MTMtMzgyZGE2MDk5YmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTAzVDExNDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxODJkMDZkMTg5OGQ1MzM1YzVkMWViZTlkYmJmZjNkZTc3MDE2MTE0YjM4OTQxYTU1ZTRkM2I0ODk5MDQ3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VLt90TTlLM4J-gtq57U-0xwqOYcwqASFNgeibxf6TUo">

Hi! I haven't encountered that issue myself, but you're right, that function can be commented out. It's leftover from a previous script and isn't used here.

If you run into any other problems, feel free to ask!
